name: saucectl cypress tests v1

on: [push]

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Sauce Connect Proxy Action
        uses: saucelabs/sauce-connect-action@v2.3.2
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelName: github-action-tunnel
          tunnelPool: true
          configFile: ${{ github.workspace }}/sc-configuration/config.yaml

      - name: Cypress with saucectl
        uses: saucelabs/saucectl-run-action@v3

  # build-app:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         install: npm install
  #         build: npm run build

  # main:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Saucectl RUN Docker and Cloud
  #       uses: saucelabs/saucectl-run-action@v3
  #       with:
  #         build: npm run build
  #         start: npm start
  # cypress-run:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     # Install NPM dependencies, cache them correctly
  #     # and run all Cypress tests
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v5.0.0 # use the explicit version number
  #       with:
  #         build: npm run build
  #         start: npm start
